const SVG = {
	purchases_one_outline_black: new URL("./Svg/purchases_one_outline_black.svg", import.meta.url).href,
	purchases_one_filled_white: new URL("./Svg/purchases_one_filled_white.svg", import.meta.url).href,
	purchases_one_outline_white: new URL("./Svg/purchases_one_outline_white.svg", import.meta.url).href,
	purchases_two_filled_white: new URL("./Svg/purchases_two_filled_white.svg", import.meta.url).href,
	purchases_two_outline_black: new URL("./Svg/purchases_two_outline_black.svg", import.meta.url).href,
	counter_filled_white: new URL("./Svg/counter_filled_white.svg", import.meta.url).href,
	counter_filled_black: new URL("./Svg/counter_filled_black.svg", import.meta.url).href,
	counter_outline_white: new URL("./Svg/counter_outline_white.svg", import.meta.url).href,
	counter_outline_black: new URL("./Svg/counter_outline_black.svg", import.meta.url).href,
	dispensary_outline_black: new URL("./Svg/dispensary_outline_black.svg", import.meta.url).href,
	dispensary_outline_white: new URL("./Svg/dispensary_outline_white.svg", import.meta.url).href,
	dispensary_filled_white: new URL("./Svg/dispensary_filled_white.svg", import.meta.url).href,
	dispensary_filled_black: new URL("./Svg/dispensary_filled_black.svg", import.meta.url).href,
	customers_filled_white: new URL("./Svg/customers_filled_white.svg", import.meta.url).href,
	vendor_one_filled_white: new URL("./Svg/vendor_one_filled_white.svg", import.meta.url).href,
	vendor_two_filled_white: new URL("./Svg/vendor_two_filled_white.svg", import.meta.url).href,
	branch_svg_repo: new URL("./Svg/branch-svgrepo-com.svg", import.meta.url).href,
	branch_colored_one: new URL("./Svg/branch_colored_one.svg", import.meta.url).href,
	branch_colored_two: new URL("./Svg/branch_colored_two.svg", import.meta.url).href,
	literal_branch_colored: new URL("./Svg/literal_branch_colored.svg", import.meta.url).href,

	// Home page
	svg_1: new URL("./Svg/svg_1.svg", import.meta.url).href,
	svg_2: new URL("./Svg/svg_2.svg", import.meta.url).href,
	svg_3_yellow: new URL("./Svg/svg_3_yellow.svg", import.meta.url).href,
	svg_3_red: new URL("./Svg/svg_3_red.svg", import.meta.url).href,
	svg_4: new URL("./Svg/svg_4.svg", import.meta.url).href,
	Finance_1: new URL("./Svg/undraw_statistic-chart_6s7z.svg", import.meta.url).href,
	// Dashboard page
	add_user: new URL("./Svg/user-plus-solid.svg", import.meta.url).href,
	users: new URL("./Svg/users-solid.svg", import.meta.url).href,
	key: new URL("./Svg/key-solid.svg", import.meta.url).href,
	profile_edit: new URL("./Svg/user-gear-solid.svg", import.meta.url).href,
	profile: new URL("./Svg/profile.svg", import.meta.url).href,
	profile_blue: new URL("./Svg/profile_blue.svg", import.meta.url).href,
	receipt: new URL("./Svg/receipt-white-svgrepo-com.svg", import.meta.url).href,
	invoice_filled: new URL("./Svg/invoice_filled.svg", import.meta.url).href,
	invoice_outline: new URL("./Svg/invoice_outline.svg", import.meta.url).href,
	invoice_coloured: new URL("./Svg/invoice_colored.svg", import.meta.url).href,
	report: new URL("./Svg/report.svg", import.meta.url).href,
	stock_rec_colored: new URL("./Svg/stock_colored.svg", import.meta.url).href,
	stock_rec_monochrome: new URL("./Svg/stock_monochrome.svg", import.meta.url).href,
	dispensary: new URL("./Svg/dispensary.svg", import.meta.url).href,
};

export default SVG;
